export enum ErrorCode {
  // Verification
  NOT_VERIFIED = "NOT_VERIFIED",
  VERIFICATION_EXPIRED = "VERIFICATION_EXPIRED",
  VERIFICATION_PENDING = "VERIFICATION_PENDING",
  INVALID_EMAIL_DOMAIN = "INVALID_EMAIL_DOMAIN",
  ALREADY_VERIFIED = "ALREADY_VERIFIED",

  // Guild
  GUILD_NOT_CONFIGURED = "GUILD_NOT_CONFIGURED",
  FEATURE_DISABLED = "FEATURE_DISABLED",

  // Profile
  PROFILE_DISABLED = "PROFILE_DISABLED",
  PROFILE_NOT_FOUND = "PROFILE_NOT_FOUND",

  // Auth
  TOKEN_EXPIRED = "TOKEN_EXPIRED",
  TOKEN_USED = "TOKEN_USED",
  TOKEN_NOT_FOUND = "TOKEN_NOT_FOUND",
  INVALID_JWT = "INVALID_JWT",

  // Suggestions
  SUGGESTIONS_DISABLED = "SUGGESTIONS_DISABLED",

  // Permissions
  INSUFFICIENT_PERMISSIONS = "INSUFFICIENT_PERMISSIONS",
  ADMIN_NOT_FOUND = "ADMIN_NOT_FOUND",

  // General
  NOT_FOUND = "NOT_FOUND",
  UNAUTHORIZED = "UNAUTHORIZED",
  VALIDATION_ERROR = "VALIDATION_ERROR",
  INTERNAL_ERROR = "INTERNAL_ERROR",
}

export class AppError extends Error {
  constructor(
    public code: ErrorCode,
    message: string,
  ) {
    super(message);
    this.name = "AppError";
  }
}
